var expect = require("expect.js");

var distanceBetweenPatternAndStrings = require("../../main/js/distanceBetweenPatternAndStrings");

describe("Distance Between Pattern and String Spec", function () {

    var pattern;
    var dnaStrings;

    it("should process short text", function () {
        //given
        pattern = "AAA";
        dnaStrings = ["TTACCTTAAC", "GATATCTGTC", "ACGGCGTTCG", "CCCTAAAGAG", "CGTCAGAGGT"];

        //when
        //then
        expect(distanceBetweenPatternAndStrings(pattern, dnaStrings)).to.be(5);
    });

    it("should process dataset", function () {
        //given
        pattern = "CACGGC";
        dnaStrings = ["TAACTAGGCTTGACGGCTCGGGTGACCGAACGGGCTACCTAGAGCAGGGAGGCGTTGACGCAACTCGCTGTCTTTGCAGGGATTTCCTGAAATAT", "TGCTGCCCTGTTATTTGATACAGTTGCAGCCCGCCCTATCCCCACAACATCATCGACACCTCAGCTTCGACCTCGATGGTCGTCCCCAAAACGTA", "TCTCAAACGCACAAGTACCATACTGATCCATATTTTGTCGAACGTCACCCCTGGCTGCTGCAGACCGCAGTTTCCCCTCACGAGAACACCTCGCA", "TGCGGTGATGTGAATTGGGACCCTCATAGCTTCCTTTAGTAGTGAAGTACAGATCGGCTCCACGGAAGATAAGGTGTGCTCGCGATCTCCTAATG", "CTGCTCCTGAAGGTGGTGTAACTCATTTGATCATCTACCACAGAATGTCTAAAGTCCTCGTTAAAGTCCATTCGTGACACAATATTGCCCCGTCA", "TTGGACGTTTATGTTACGTGGAGGATAAACGCAATTTTGTGAGAGAGGTCCACCGACCCTGTGTCGTGATGGCGAATGCAAAATAATCCCCGAAA", "TACTTTAGGTACCAGAATGTAGCAATGCATCAGGATGGTAGGCTTGCGTACCACCGGCGCGAGGGGATAGAGAGTTAAAGATCAATCGAATTAGG", "TAACACGAATGCCGAAAGAGGGAGGGGGCAGAGTGGGTCGGGCCGCAGGGGTAAGGTGTCTACTCTTGGAATAAGCTGCAACGAAATAATTTAAC", "ATAAGGCTCCAGAAAGGAGGGAGCAAATGACTACCAAATAGAAGGCTTAATTCCTATCCTACTTATGCCCCATCGGCAACTCAGGGGGGCGGAGA", "CTCTGGACTCGGCTGCCTGACGTCGTCTTTGGTACGTATCTACTATATGTTCTTACTCTCTTTGACGTACATGAATATATAAGCACCGTTAACAT", "GAGGCAATCAGACCGAAGTATAAAGAACGTTGTCCCGCCTATAAAAAACTACGAAAAGCTTGTACTGCAACGGAGCGTAGAAACAACCGGACGTA", "AAAAGACCAGATCTCGCCCCAGCGACGGGAACACCGGTATCGCCTTAGGCGGCACGATTACAGAGTTCGTCCTTCAGTAAGCTATTCATGACCCG", "TCGACGTATTCTCACCGTTATTTTCGACTACTAGCGAATCGGCCATTTCGGCTGCCTGGGTACCACAACGGCCGAATTCGGACGATTGGAGTTAA", "CATCGCGGGCAGTGTCGGGGATAGCCAACGAATCATTGGAAAACGCGTAACCGACTTATAATATGTTTAACAGCTTTGGGACCTATTAATTCGGT", "CCGGGCCATGACCCGGCCCAGTATGGAAGTGTGTAGAACAACGAGTCCGCAGTAGAATGTCGCGGAGTTCTGTACAGTTCGGCCTAACGAGATTA", "GACGTTTGCCCCATGAGTGCACGCACACTCACCTGTCAGGCTAGAGCGGAACCTACGTACCATTGTGGGCAAGGGTTTAGTAATTTATAGGTATC", "TCTCGTCATGGGCAATCGTAGAGTGGATCGGGGCAACAACCGATGTTCCGCTATGTACTGCAGTAGACGACTAAGGCGCGTGCAAGCGCGTTCGT", "TATATCTGAGCGAATCTGCATAGGACCCCGCATCCTGCAGACTTGATTTAATTATGCGTAAACTACATGAGCCTCCATGGCAGTCAGTTGGGATC", "AAAGGGCCACAACAATCTCCACTTGTGCGGCACTATCCGGCAAGCGCGCTGTTATAGCGCCCACAGTGCGATCCCGGAAGTTGCAAGTAGCGTCC", "AATTGGTCATTCGGTCCTTCCGGTAATCGACCACGCAGACAGATCTCCGTCTTAATTCACACAGCAACCGAGGGCCATAATCCCCTGCTCTCTAC", "AAAGTTACAACGTTTCGCTGCTGGTTGGCCGAATGTATATGGTGCAACAACATTTGAGACAAGCTTCCATCCGACGGAACTCCTAGATAGAAGTT", "TGTGCGGCACTGCACCTGTGGAATAAGAGCTCGTGCACCAGCGCCGCTTCATAAACATTGCACTTAGGCGCTGATTACTTACTCGGTCACGAATG", "GAGGGGCTCACTTCACGATGGTCGACGGCGCGTCCATAGGAATACAATTTAGTCGTCGGTAACAGGCAGGCCGGCATAGCGCAGGGTCCGAGACA", "CGGGTTCGTTAGACGTTAAAGGCCGACTATGAAATACTATGACTAGCAACCATAAGCCTGTTTAAGACCTAAGGATGGTTAATCTTCCGTACCCG", "TCTACACATCTCGGCTTGTAGTGGAGCGTACTTAGAAAGCGCGATATGTGTCCTAATCTATAGTACCTTCAGAAAGTCGAGTCCAGCGGGTGCTT", "TTCTCAATATTAGAACCCAAGCTGGGGCTATTAAACCACATCCCCACGCGCATGACGCCACCAATTTCTCAGTAGATTATCTGTCCGACTCGGGG", "GGGTAGAGCTAGCAGGCACGTCAGCCCTAACCTGTTAAGCATCATCTGATAAGCAGCCTATCCATATCGGCCCAGTTAGGAGCATTTTAGCCGCA", "CTGTGTCAGCGCGTTTGAAGCATTCGCGTAGAAGCCCATGACAGCTCGTACGTGCAGCGATACGTCACAACCAGAACGACGTGGTGCTGCTATTA", "TACTTGTAACGGGAAGCTGGGAAATTCGAACCCCATATCTTAGAAAATCGCCACAGCGCTTCTTGACCTAAAGACAGAGTATAGCTGATGCTATA", "CTCGTTGTCTACGCGATTTAGGACCCACCTAGAGGCAGTCTTGTCCAAGATCCTTACCCAATTATCGGACCTGAACCCTGTAGATATTTTCTTTA", "CCGAGGCACTGAGCCGCACAGAGAAAGGTCTATTAAGTTGAGTGGCTATGGCCCGGTAACATCGGTTAAATAAGAACAATAGTAGTTACGGCGCG", "CGAACGGCTCGCGATAAGGTCGATCGAGTATCTCCACATGATGACGTGGAGACTTCGATTTAGTAGGTCCAGTATGTGTTGTTACCGATTTTGTG", "TGAGTGGGGCTATACGAATGAGCACAGCAAGGTGAGTTCCGGGACTGTTGTTATCACTTCAACGAACTCGGTGTCTAACTCACAAGTGCTCGCGG"];

        //when
        //then
        expect(distanceBetweenPatternAndStrings(pattern, dnaStrings)).to.be(52);
    });
});