var expect = require("expect.js");

var frequentPatterns = require("../../main/js/frequentPatterns");

describe("Frequent Patterns Spec", function () {

    var text;
    var k;

    it("should process short text", function () {
        //given
        text = "ACGTTGCATGTCGCATGATGCATGAGAGCT";
        k = 4;

        //when
        //then
        expect(frequentPatterns(text, k)).to.eql(["GCAT", "CATG"]);
    });

    it("should process extra dataset", function () {
        //given
        text = "CGGAAGCGAGATTCGCGTGGCGTGATTCCGGCGGGCGTGGAGAAGCGAGATTCATTCAAGCCGGGAGGCGTGGCGTGGCGTGGCGTGCGGATTCAAGCCGGCGGGCGTGATTCGAGCGGCGGATTCGAGATTCCGGGCGTGCGGGCGTGAAGCGCGTGGAGGAGGCGTGGCGTGCGGGAGGAGAAGCGAGAAGCCGGATTCAAGCAAGCATTCCGGCGGGAGATTCGCGTGGAGGCGTGGAGGCGTGGAGGCGTGCGGCGGGAGATTCAAGCCGGATTCGCGTGGAGAAGCGAGAAGCGCGTGCGGAAGCGAGGAGGAGAAGCATTCGCGTGATTCCGGGAGATTCAAGCATTCGCGTGCGGCGGGAGATTCAAGCGAGGAGGCGTGAAGCAAGCAAGCAAGCGCGTGGCGTGCGGCGGGAGAAGCAAGCGCGTGATTCGAGCGGGCGTGCGGAAGCGAGCGG";
        k = 12;

        //when
        //then
        expect(frequentPatterns(text, k)).to.eql(["GGAGAAGCGAGA", "GCGTGGCGTGCG", "CGTGGCGTGCGG", "CGGCGGGAGATT", "GGCGGGAGATTC", "GCGTGGAGGCGT", "CGTGGAGGCGTG", "GCGTGCGGCGGG", "CGTGCGGCGGGA", "GTGCGGCGGGAG", "TGCGGCGGGAGA", "CGGGAGATTCAA", "GGGAGATTCAAG", "GGAGATTCAAGC"]);
    });

    it("Should process data challenge", function () {
        //given
        text = "GTTGTCGCAGTTGTCGCAAAAATTCTAGCACGCGCAAATAGGTAAGCACGCGAGCACGCGCAAATAGGTAGTTGTCGCAAGCACGCGGTTGTCGCAGTTGTCGCAAAAATTCTGTTGTCGCAGTTGTCGCAGTTGTCGCAAGCACGCGAAAATTCTAAAATTCTAAAATTCTGTTGTCGCACAAATAGGTAAAAATTCTGTTGTCGCAGAAACGTCCAAATAGGTACAAATAGGTAAGCACGCGAAAATTCTGAAACGTCCAAATAGGTAAAAATTCTGTTGTCGCAAGCACGCGGTTGTCGCAGTTGTCGCAAGCACGCGAGCACGCGGAAACGTCGAAACGTCGTTGTCGCAGTTGTCGCAAGCACGCGAAAATTCTGAAACGTCAAAATTCTAAAATTCTGAAACGTCAGCACGCGAGCACGCGGTTGTCGCAAAAATTCTGTTGTCGCAAAAATTCTGTTGTCGCAGTTGTCGCACAAATAGGTAAAAATTCTAGCACGCGGTTGTCGCAGAAACGTCGAAACGTCGAAACGTCGTTGTCGCACAAATAGGTACAAATAGGTACAAATAGGTAAAAATTCTGTTGTCGCAAAAATTCTAAAATTCTGAAACGTCAGCACGCGAGCACGCGCAAATAGGTAGTTGTCGCAGAAACGTCCAAATAGGTAGTTGTCGCAAGCACGCGCAAATAGGTAAAAATTCTAGCACGCGAAAATTCTGAAACGTCGTTGTCGCACAAATAGGTACAAATAGGTAAGCACGCGCAAATAGGTACAAATAGGTAAAAATTCTGTTGTCGCACAAATAGGTACAAATAGGTAGTTGTCGCAAAAATTCTGAAACGTCAGCACGCGGTTGTCGCACAAATAGGTAAGCACGCGAGCACGCGAAAATTCTAGCACGCGGTTGTCGCAAAAATTCTAGCACGCGAGCACGCGGAAACGTCAGCACGCGCAAATAGGTAGTTGTCGCACAAATAGGTA";
        k = 11;
        expect(frequentPatterns(text, k)).to.eql(["ACAAATAGGTA"]);
    })

});