var expect = require("expect.js");

var motifEnumeration = require("../../main/js/motifEnumeration");

describe("Motif enumeration Spec", function () {

    var dnaStirngs;
    var k;
    var d;

    it("should process short text", function () {
        //given
        k = 3;
        d = 1;
        dnaStirngs = ["ATTTGGC", "TGCCTTA", "CGGTATC", "GAAAATT"];

        //when
        //then
        expect(motifEnumeration(k, d, dnaStirngs).join(" ")).to.be("ATA ATT GTT TTT");
    });

    it("should process extra dataset", function () {
        //given
        k = 5;
        d = 2;
        dnaStirngs = ["TCTGAGCTTGCGTTATTTTTAGACC", "GTTTGACGGGAACCCGACGCCTATA", "TTTTAGATTTCCTCAGTCCACTATA", "CTTACAATTTCGTTATTTATCTAAT", "CAGTAGGAATAGCCACTTTGTTGTA", "AAATCCATTAAGGAAAGACGACCGT"];

        //when
        //then
        expect(motifEnumeration(k, d, dnaStirngs).join(" ")).to.be("AAACT AAATC AACAC AACAT AACCT AACTA AACTC AACTG AACTT AAGAA AAGCT AAGGT AAGTC AATAC AATAT AATCC AATCT AATGC AATTC AATTG ACAAC ACACA ACACC ACACG ACACT ACAGA ACAGC ACATC ACATG ACCAT ACCCT ACCGT ACCTA ACCTC ACCTG ACCTT ACGAC ACGAG ACGAT ACGCT ACGGT ACGTC ACGTT ACTAA ACTAG ACTAT ACTCA ACTCC ACTCG ACTCT ACTGA ACTGC ACTGT ACTTA ACTTC ACTTT AGAAA AGAAC AGAAG AGAAT AGACA AGACT AGATA AGATC AGCAT AGCCA AGCGT AGCTA AGCTC AGCTG AGCTT AGGAT AGGTA AGGTC AGTAA AGTAC AGTAT AGTCC AGTCG AGTCT AGTGA AGTTG ATAAA ATAAC ATACA ATACC ATAGA ATATA ATATC ATATG ATATT ATCAG ATCCC ATCCG ATCCT ATCGA ATCGC ATCTA ATCTC ATCTG ATGAC ATGAT ATGCA ATGCC ATGGA ATGGC ATGTA ATGTC ATTAA ATTAC ATTAG ATTAT ATTCA ATTCC ATTCG ATTGA ATTGC ATTGG ATTGT ATTTA ATTTC ATTTG ATTTT CAAAG CAACC CAACT CAAGA CAAGC CAATA CAATT CACAC CACAG CACCT CACGT CACTA CACTT CAGAA CAGAC CAGAT CAGGT CAGTA CAGTC CATAA CATAC CATAG CATAT CATCC CATCT CATGA CATGT CATTA CATTG CATTT CCAAG CCATA CCATG CCATT CCCGT CCCTA CCCTT CCGAA CCGAC CCGAT CCGCT CCGGT CCGTA CCGTC CCGTG CCGTT CCTAC CCTAT CCTCA CCTCC CCTTA CCTTC CCTTG CCTTT CGAAA CGAAG CGACA CGACT CGAGT CGATA CGATG CGATT CGCAA CGCAT CGCCA CGCGA CGCTA CGCTC CGCTT CGGAC CGGAT CGGCA CGGTA CGGTC CGGTT CGTAA CGTAC CGTCA CGTCG CGTCT CGTTA CGTTT CTAAC CTAAG CTAAT CTACA CTACC CTACG CTACT CTAGA CTAGC CTAGG CTAGT CTATA CTATC CTATG CTATT CTCAT CTCCG CTCGT CTCTA CTCTT CTGAA CTGAG CTGCA CTGCC CTGTA CTGTT CTTAA CTTAC CTTAG CTTAT CTTCA CTTGA CTTTA CTTTC CTTTG CTTTT GAAAT GAACA GAACT GAAGT GAATG GAATT GACAC GACAT GACCA GACCT GACGT GACTT GAGAA GAGAT GAGCT GATAA GATAC GATAG GATAT GATCA GATCC GATCG GATCT GATGT GATTA GATTC GATTG GATTT GCAAT GCACT GCATC GCATT GCCAT GCCGT GCCTA GCCTT GCGAT GCGGT GCGTC GCGTT GCTAA GCTAC GCTAG GCTAT GCTGA GCTGT GCTTA GCTTT GGAAT GGACA GGATA GGATC GGATT GGCTA GGGAT GGTAC GGTAG GGTAT GGTCA GGTCG GGTTA GTAAA GTAAG GTACA GTACC GTACG GTAGA GTATA GTATC GTATG GTATT GTCAA GTCAG GTCCG GTCCT GTCGA GTCGC GTCGT GTCTA GTCTG GTGAA GTGAG GTGCA GTGCG GTTAA GTTAC GTTAG GTTAT GTTCA GTTCC GTTCG GTTGA GTTTA TAAAC TAAAG TAACA TAACC TAACT TAAGA TAAGC TAATA TAATC TACAC TACAG TACCC TACCG TACCT TACGA TACGC TACGT TACTA TACTC TACTG TAGAA TAGAC TAGAG TAGAT TAGCC TAGCG TAGGA TAGTC TATAA TATAC TATAT TATCA TATCC TATCG TATGA TATGC TATGG TATGT TATTA TATTG TCAAC TCAAT TCACC TCACG TCACT TCAGA TCATA TCATG TCCAA TCCAC TCCAG TCCAT TCCCA TCCCT TCCGA TCCGC TCCGT TCCTA TCCTG TCCTT TCGAA TCGAC TCGAT TCGCC TCGCT TCGGA TCGGC TCGGG TCGGT TCGTC TCTAC TCTAG TCTAT TCTCC TCTCT TCTGG TCTGT TCTTA TCTTT TGAAA TGAAC TGAAT TGACA TGACC TGACT TGAGA TGAGC TGAGT TGATA TGATC TGATG TGATT TGCAA TGCAC TGCAG TGCAT TGCCA TGCCG TGCCT TGCGA TGCGT TGCTT TGGAA TGGAT TGGTA TGTAA TGTAG TGTAT TGTCC TGTCG TGTGG TGTTA TTAAA TTAAC TTAAG TTAAT TTACA TTACC TTACG TTACT TTAGA TTAGC TTAGG TTAGT TTATA TTATC TTATG TTATT TTCAA TTCAC TTCAT TTCCA TTCCC TTCCT TTCGA TTCGG TTCGT TTCTA TTCTG TTGAA TTGAC TTGAG TTGAT TTGCA TTGCG TTGGA TTGGG TTGTG TTTAA TTTAC TTTAG TTTAT TTTCA TTTCC TTTCG TTTGA TTTGG TTTTA TTTTG");
    });

    it("should process data challenge", function () {
        //given
        k = 5;
        d = 2;
        dnaStirngs = ["TATGTGTTAACCATTGCTCCCTCAC", "AAGAGTGGATTTGGAATCATGCATT", "ACCAAATCAAGTACATGAGCCCAAG", "AACAGGGTATCGGGGATCACATGGG", "TTCAAATCAGACCCCGGGCTTAATA", "GATTATTCATATGTCGTCTTTCCCG"];

        //when
        //then
        expect(motifEnumeration(k, d, dnaStirngs).join(" ")).to.be("AAAAT AAACA AAACG AAAGT AAATA AAATC AAATG AAATT AACAT AACCA AACCC AACCG AACTA AACTC AACTG AACTT AAGAT AAGCA AAGGC AAGTA AAGTG AAGTT AATAA AATAC AATAG AATAT AATCA AATCC AATCG AATCT AATGA AATGC AATGG AATGT AATTA AATTG ACAAG ACAAT ACACA ACATA ACATC ACATG ACATT ACCAG ACCAT ACCCA ACCGG ACCGT ACCTG ACCTT ACGAC ACGCA ACGCG ACGTA ACGTG ACTAG ACTCA ACTCG ACTGA ACTTA ACTTC ACTTG ACTTT AGAAT AGACA AGATA AGATC AGATG AGATT AGCAT AGCCG AGCCT AGCGT AGCTG AGCTT AGGAT AGGCA AGGCG AGGCT AGGGC AGGTT AGTAA AGTAC AGTCA AGTCT AGTGA AGTTA AGTTC AGTTT ATAAA ATAAC ATAAG ATAAT ATACA ATACC ATACG ATAGA ATAGC ATAGG ATAGT ATATA ATATC ATATG ATATT ATCAA ATCAC ATCAG ATCAT ATCCA ATCCC ATCCG ATCCT ATCGA ATCGC ATCGG ATCGT ATCTA ATCTC ATCTG ATCTT ATGAA ATGAC ATGAG ATGAT ATGCA ATGCC ATGCG ATGCT ATGGC ATGGG ATGTC ATGTG ATTAA ATTAC ATTAG ATTAT ATTCA ATTCC ATTCG ATTGA ATTGG ATTTC ATTTG CAAAC CAAAG CAAAT CAAGT CAATC CAATG CAATT CACAC CACAG CACAT CACCC CACGT CACTC CACTT CAGAC CAGAG CAGGT CAGTA CAGTC CAGTT CATAA CATAC CATAG CATAT CATCA CATCC CATCG CATCT CATGA CATGC CATGG CATGT CATTA CATTC CATTT CCAAT CCACG CCACT CCATA CCATC CCATG CCATT CCCAT CCCTG CCCTT CCGAT CCGTG CCTCA CCTGC CCTGT CCTTG CGAAT CGAGT CGATA CGATC CGATT CGCAT CGCCT CGCGT CGGGT CGTAA CGTAC CGTAG CGTAT CGTCA CGTGA CGTGC CGTGG CGTGT CGTTC CTAAT CTACA CTAGC CTATC CTATT CTCAA CTCAC CTCAG CTCAT CTCGA CTCGT CTGAT CTGGT CTGTA CTGTG CTTAC CTTAG CTTAT CTTCA CTTGA CTTGC CTTGG CTTGT GAAAA GAACA GAATC GAATG GAATT GACAT GACCA GACCC GACCG GACCT GACGA GACGT GACTA GACTC GACTT GAGAA GAGAT GAGCA GAGGT GAGTA GAGTC GAGTT GATAA GATAC GATAT GATCA GATCC GATCG GATCT GATGA GATGC GATTA GATTC GCAAA GCACA GCACG GCAGT GCATA GCATC GCATG GCATT GCCAT GCCTA GCCTC GCCTG GCGCG GCGGC GCGTA GCGTC GCGTG GCTCA GCTCT GCTGA GCTTA GCTTG GGAGT GGATA GGCAT GGCCT GGCTA GGCTC GGGCT GGGTA GGGTC GGTAA GGTAT GGTCA GGTGA GGTTC GTAAG GTAAT GTACC GTACT GTAGA GTAGT GTATA GTATC GTATT GTCAA GTCAC GTCAG GTCAT GTCCA GTCGA GTCTA GTGAC GTGAT GTGCA GTGCC GTGCT GTGGC GTGGG GTGTA GTTAA GTTAG GTTCA GTTCT GTTGA GTTTA TAAAA TAAAT TAACA TAACC TAACG TAAGA TAAGG TAATA TAATC TAATG TACAA TACAC TACAT TACCA TACCT TACGG TACTG TACTT TAGAT TAGCT TAGGA TAGGC TAGTA TAGTG TATAA TATAC TATAT TATCA TATCC TATCG TATCT TATGA TATTA TATTC TATTT TCAAA TCAAC TCAAG TCAAT TCACA TCACC TCACG TCACT TCAGC TCAGT TCATA TCATC TCATG TCATT TCCAA TCCAC TCCAG TCCAT TCCCG TCCCT TCCGA TCCGG TCCGT TCCTA TCCTG TCGAC TCGAT TCGCA TCGCG TCGTA TCGTG TCTAA TCTAT TCTCA TCTCG TCTGA TCTGC TCTGG TCTTG TGAAA TGAAT TGACA TGACG TGACT TGAGA TGAGG TGAGT TGATA TGATC TGATG TGATT TGCAC TGCAG TGCAT TGCCA TGCCG TGCGG TGCGT TGCTC TGGAC TGGAT TGGGC TGGGG TGGGT TGGTA TGGTC TGTAA TGTAT TGTCA TGTGA TTAAA TTACA TTACG TTAGA TTAGC TTAGG TTATA TTATC TTATG TTCAA TTCAC TTCAG TTCAT TTCCA TTCGC TTCGT TTGAC TTGAG TTGAT TTGCA TTGGC TTGTA TTTAC TTTAG TTTAT TTTCA");
    });


});